[package]
name = "plex_proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
# hyper-reverse-proxy = { git = "https://github.com/felipenoris/hyper-reverse-proxy"}
# plex-api = "0.0.5"
plex-api = { git = "https://github.com/andrey-yantsen/plex-api.rs" }
pretty_assertions = "1.3.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde-xml-rs = "0.6.0"
serde_json = "1.0.92"
hyper = { version = "0.14.24", features = ["full"] }
tokio = { version = "1.25.0", features = ["full"] }
lazy_static = "1.4.0"
# hyper-trust-dns = "0.5.0"
# simple_proxy = "1.3.4"
# hudsucker = "0.19.0"
# warp-reverse-proxy = "1.0.0"
warp = "0.3.3"
pretty_env_logger = "0.4.0"
hyper-reverse-proxy = "0.5.1"
anyhow = "1.0.69"
