version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      # claim from https://plex.tv/claim 
      - PLEX_CLAIM=
    ports:
      - 32400:32400
    # volumes:
    #   - /path/to/library:/config
    #   - /path/to/tvseries:/tv
    #   - /path/to/movies:/movies
    restart: unless-stopped
  replex:
    image: ghcr.io/sarendsen/replex:latest
    container_name: replex
    environment:
      REPLEX_HOST: http://plex:32400
      TEST: plex
    ports:
      - 3001:80
    restart: unless-stopped
    depends_on:
      - plex
